from cores.state import State
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from typing import List
from llm import llm
from console import console
from pathlib import Path
from typing import Literal
from cores.schemas import RouteDecision, RouterOutput
from cores.error_codes import StateError, StateErrorCode


async def node_router(state: State) -> State:
    """
    Route each research subquery to the most appropriate retrieval tools.

    This node receives the structured research plan from the Planner and
    determines which tools should be used for each subquery.

    Returns:
        Updated state containing structured routing decisions for each subquery.
    """

    # Uploaded documents
    documents_dir = Path("documents")
    document_files = [f.name for f in documents_dir.iterdir() if f.is_file()]

    # Local vector database source documents
    local_db_dir = Path("local_documents")
    local_db_files = [f.name for f in local_db_dir.iterdir() if f.is_file()]
    Messages = [
        SystemMessage(content=f"""You are the Router of a healthcare research assistant.

            Your task is to analyze the research plan generated by the Planner and
            select the most appropriate retrieval tools for each subquery.

            Available tools:
            - research_tavily: General web search, news, official websites, and
            non-academic information.
            - search_pubmed: Biomedical and medical literature.
            - search_arxiv: AI, computer science, and quantitative research papers.
            - document_qa: Search documents uploaded during the current session.
            - local_knowledge: Search the persistent local vector database.

            Current uploaded documents:
            {document_files}

            Current local knowledge documents:
            {local_db_files}
                      
            Routing rules:
            1. For each subquery, FIRST check whether any current uploaded document
            is relevant based on its filename or topic.

            2. If an uploaded document is relevant, you MUST include "document_qa"
            in the tools list.

            3. If a local knowledge document is relevant, you MUST include
            "local_knowledge".

            4. You may include external tools such as PubMed, arXiv, or Tavily
            in addition to document_qa/local_knowledge.

            5. For example, if the uploaded documents include
            "benefits_of_remote_work.pdf" and the subquery asks about
            benefits or outcomes of remote work, select "document_qa".

            6. Multiple tools may be selected for the same subquery.
            """),
        HumanMessage(content=f"""Research plan: {state["research_plan"]}"""),
    ]

    structured_llm = llm.with_structured_output(RouterOutput)

    console.rule("[bold cyan]Router")

    with console.status("Router selecting retrieval tools..."):
        try:
            msg = await structured_llm.ainvoke(Messages)

            return {
                "router": msg,
            }

        except Exception as e:
            error = StateError(
                code=StateErrorCode.ROUTER_LLM_ERROR,
                message=str(e),
                node="planner",
                retryable=True,
            )

            return {
                "errors": [error],
            }
